### ISSUE TITLE
Corrupted sine wave with Wideband SDR Transceiver

### ISSUE THREAD

**Issue by dxxx9** [pavel-demin/red-pitaya-notes#1060]
### Description of the setup:

 * Device: Red Pitaya 125-14
 * SD card image: your Alpine image
 * Application: Wideband SDR Transceiver

### Description of the problem:

Hello Pavel,

I looked at #930 because I'm also interested in baseband transmission. My flowgraph is similar to [yours](https://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-wide/). OUT1 is connected with IN1. But the received sine wave doesn't look like expected at all. This happens for the higher selectable sample rates (most severe at 2500 kSPS). See image below.

<img width="1359" alt="sin_res2" src="https://user-images.githubusercontent.com/62398752/185922376-cff86181-0b3f-44a4-83d7-d00c885e19f9.png">

There are arbitrary phase shifts and parts where there is no signal at all.

As I'm not sure how to find the source of error, I'm writing this issue.
Can this be caused by the network connection?

**Comment by pavel-demin** [comment]
The "Sample Rate" fields in the Red Pitaya blocks of your diagrams are empty. So maybe these blocks do not run at the same sample rate as the other two blocks.

**Comment by dxxx9** [comment]
Thanks for your reply. The sample rate is not the issue. See the images below for 0.5MSPS, 1.25MSPS and 2.5MSPS.

0.5MSPS works fine 100% of the time.
<img width="1344" alt="sin500" src="https://user-images.githubusercontent.com/62398752/186122509-6a9113ad-3264-45c0-b141-efd5d6c7f4a8.png">

1.25MSPS results are as expected 50% of the time.

https://user-images.githubusercontent.com/62398752/186126096-8b76a114-bded-474e-b6f5-00e64e6b0e40.mov



2.5MSPS has those gaps and arbitrary phase shifts all the time.
<img width="1340" alt="sin2500" src="https://user-images.githubusercontent.com/62398752/186122672-83e694e0-c3d0-4cb8-a9a5-532911e9239f.png">

What I noticed with the 2.5MSPS rate, is that the pattern of the phase shifts (or the new waveform) is almost the same for multiple periods, until the next gap. Then a new pattern starts.
<img width="1310" alt="pattern" src="https://user-images.githubusercontent.com/62398752/186130063-a11884fb-02f1-43ba-a039-ec8858cc0ce2.png">



- Do you have any clue how to narrow down the error?
- Could this be caused by network issues?
- Can you reproduce this issue when choosing the upper sample rates?

**Comment by pavel-demin** [comment]
Thank you for the tests.

I think I have not tested 2.5 MSPS before because I did not have a fast Linux computer to run GNU Radio at that sample rate.

I just did some tests:

 - 1.25 MSPS rate works without problem
![trx_wide_1250](https://user-images.githubusercontent.com/8037893/186146962-fd546ce2-a943-4684-a901-2fed1fbec63c.png)

 -  2.5 MSPS rate does not work well
![trx_wide_2500](https://user-images.githubusercontent.com/8037893/186147497-8921364c-47fb-48d6-be61-4d22e056a2ee.png)

The CPU load on the Red Pitaya board is quite high. It seems that setting the RX and TX sample rate to 2.5 MSPS does not work for this application.

**Comment by dxxx9** [comment]
Ok, thanks for your time and confirming this issue.

Interesting that your 1.25MSPS signal looks fine. Did you use the `RP 125-14` as well?

**Comment by pavel-demin** [comment]
Yes, I used Red Pitaya 125-14 for the tests. I connected the Ethernet ports of the Red Pitaya board and my computer directly with a good CAT6 cable.

**Comment by dxxx9** [comment]
Thank you Pavel, for the clarification.
If I understand correctly, you are assuming that the CPU is the limiting factor in this case?

I am transmitting PAM in baseband and that is why I have set the carrier frequency to zero.
Is it possible to increase the receive bandwidth further?
It seems to me that the board is designed for radio applications that use carrier modulation. The fast ADC allows passband transmission up to 60 MHz, but without DDS the CPU rate is not sufficient to generate baseband signals with the same frequency (about 60 MHz). Correct?

Greetings, Daniel

**Comment by pavel-demin** [comment]
Most of the projects in this repository aim for simplicity rather than high performance to show that fairly simple techniques can be used to build some interesting applications for the Red Pitaya board. It should be possible to alleviate some bottlenecks using more complicated techniques.

> Is it possible to increase the receive bandwidth further?

The [sdr_receiver_wide_122_88](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/sdr_receiver_wide_122_88) project has two RX channels with a maximum sample rate of 10.24 MSPS per channel. I think that it should be possible to modify it to have one RX channel with a maximum sample rate of 15.36 MSPS.

**Comment by dxxx9** [comment]
Alright, thanks again!

**Comment by pavel-demin** [comment]
The better performing version the wideband SDR transceiver is now in the [new release](https://github.com/pavel-demin/red-pitaya-notes/releases/tag/20230705).
