### ISSUE TITLE
mcpha: description in projects/mcpha/app/index.html still refers to old (tcl/tk) version 

### ISSUE THREAD

**Issue by GuenterQuast** [pavel-demin/red-pitaya-notes#1123]
### Description of the setup:

 * Device: Red Pitaya 125-15 
 * SD card image: red-pitaya-alpine-3.18-armv7-20231004
 * Application: mcpha 
 * Other relevant information:

### Description of the problem:

The description to start the client program is out-dated in file projects/mcpha/app/index.html
 Should say: execute client program via "python3 mcpha.py" 

In addition, I cannot start the pulse generator. 

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment]
Thank you for testing the MCPHA application and for finding this problem.

I have just updated the instructions in the [index.html](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/mcpha/app/index.html) file and in the notes.

We recently started using this application for laboratory exercises at our university and I am in the process of adding new features based on the feedback that I have received so far. Since the [20231004](https://github.com/pavel-demin/red-pitaya-notes/releases/tag/20231004) release I have added some changes that probably break the instructions for Linux. I think that at the moment the simplest workaround would be to checkout the `20231004` tag after cloning the repository and before running the control program:
```
git clone https://github.com/pavel-demin/red-pitaya-notes
cd red-pitaya-notes/projects/mcpha/client
git checkout 20231004
python3 mcpha.py
```

To start the pulse generator you will need to load a file with a spectrum. Here is a link to an example spectrum file:
https://www.dropbox.com/scl/fi/ytn019wlmvorp74afv0df/test.gen?rlkey=qu4m9q8693quf316wmymo02j1&dl=1
