### ISSUE TITLE
ExtIO_RedPitaya_TRX.dll, not possible to tx in HDSDR

### ISSUE THREAD

**Issue by mike6000** [pavel-demin/red-pitaya-notes#215]
Hi, when I try to select TX in HDSDR I get a message that TX is not supported. I have the latest version of HDSDR per 16.April.16 and use the ExtIO_RedPitaya_TRX.dll downloaded from the link on your site. I would like to tx with HDSDR

**Comment by pavel-demin** [comment]
The error message is correct. This ExtIO does not support TX. I could not find any documentation or example of how to implement this functionality.

This problem was already discussed in https://github.com/pavel-demin/red-pitaya-notes/issues/114

There is also a similar issue in the ExtIO_HackRF project: https://github.com/jocover/ExtIO_HackRF/issues/6

I suggest to try [SDR transceiver compatible with HPSDR](http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr/). It works with several excellent SDR programs that support the HPSDR/Metis communication protocol.

There are currently two ways to setup this SDR transceiver:
 - download and install small customized SD card image following the instructions from the above link
 - or download the latest Red Pitaya SD card image from http://redpitaya.com/quick-start and install the "SDR transceiver compatible with HPSDR" application from the Red Pitaya application marketplace http://bazaar.redpitaya.com
