### ISSUE TITLE
HPSDR Thetis Protocol

### ISSUE THREAD

**Issue by ptamike** [pavel-demin/red-pitaya-notes#381]
Hi Pavel,

I'm enjoying using the Red Pitaya with your software but it could be even better if it supported the HPSDR Thetis protocol. Simon Brown is supporting this with his excellent SDR-Console V3 software and will be including full transceive operation.

Thanks for your hard work on this project,

Mike - G4WNC

**Comment by pavel-demin** [comment]
Hi Mike,

Thank you for your encouraging feedback for your kind words. I'm glad that you're enjoying my software.

Currently, I'm not very interested in implementing the new HPSDR protocol. There is still no TX capable software that supports it: SDR-Console V3 is still a preview with disabled TX, Thetis isn't released yet. 

Best regards,

Pavel

**Comment by pavel-demin** [comment]
Just found that Thetis installers can be downloaded from the following link:
http://svn.tapr.org/repos_sdr_hpsdr/trunk/W5WC/Thetis_Installers/

**Comment by ka6s** [comment]
Pavel - My understanding is that pihpsdr does support transmit for the new
protocol.

Steve

On Mar 3, 2017 5:57 AM, "Pavel Demin" <notifications@github.com> wrote:

Just found that Thetis installers can be downloaded from the following link:
http://svn.tapr.org/repos_sdr_hpsdr/trunk/W5WC/Thetis_Installers/

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pavel-demin/red-pitaya-notes/issues/381#issuecomment-283959341>,
or mute the thread
