### ISSUE TITLE
sdr transceiver wide at 5 Mhz

### ISSUE THREAD

**Issue by madmaxII** [pavel-demin/red-pitaya-notes#480]
Hello Pavel, 

is it possible to configure the sdr transceiver wide to 5Mhz bandwidth?

I tried to set the CIC with R = 10 (using the script to generate fir coefficients), but it does not work well.

Thanks in advance.

**Comment by pavel-demin** [comment]
Setting the CIC decimation rate isn't enough. You'll also need to change the FIR sample rate. But the problem is that after these change this configuration won't fit into the Red Pitaya FPGA. I'd suggest to try the following changes:
 - make the CIC decimation rate fixed,
 - reduce all data and coefficient width by 4 or 8 bits.
