### ISSUE TITLE
Flock

### ISSUE THREAD

**Issue by davidhay45** [pavel-demin/red-pitaya-notes#779]
### Description of the setup:

 * Device:
 * SD card image: 3.8
 * Application: wspr (receive only set in wspr.cron)
 * Other relevant information:

### Description of the problem:

 * Call to flock failed: Resource temporarily unavailable
 * Call to flock failed: Resource temporarily unavailable

### Steps to reproduce the problem:

 1. PUTTY to RP
 2. from apps/sdr_transceiver_wspr  do ./start.sh

**Comment by pavel-demin** [comment]
There isn't much information on the web about this problem. A post on the gentoo forum indicates that the message appears after a Linux kernel update:

https://forums.gentoo.org/viewtopic-t-1088724.html

**Comment by davidhay45** [comment]
I wonder if other users of Alpine version 3.8 get the message but don't see because they are not running from the command line.  It does seem benign.  I did not notice it on 3.6.

**Comment by pavel-demin** [comment]
The error messages appears when the stop scripts in sdr_transceiver_ft8 and sdr_transceiver_wspr are running simultaneously and both are restarting the dcron service.

It's now fixed with these two commits: https://github.com/pavel-demin/red-pitaya-notes/commit/0ddf293b91f35f4064be0684185131be9e718a34 and https://github.com/pavel-demin/red-pitaya-notes/commit/7d39d807c12007185f34e82f9264adc061c4a2bb.

**Comment by pavel-demin** [comment]
The fixed version of the stop scripts for sdr_transceiver_ft8 and sdr_transceiver_wspr is now in the latest release. Closing this issue.
