### ISSUE TITLE
Problem with LPF and BPF swithing through Alexiares interface when QUISK controls the HPSDR server.

### ISSUE THREAD

**Issue by satfan52** [pavel-demin/red-pitaya-notes#785]
I build an Alexiares interfaces this weekend with 4*74HC595 as I wanted to compare with the I2C interface tried earlier this week to see if QUISK users are more Lucky with Alexiares than with the I2C interface.  I tested the interface with both PowerSDR and QUISK, as usual it  works perfectly with PowerSDR but there is unfortunately some problems with QUISK.

![image](https://user-images.githubusercontent.com/14941529/49691467-4394b580-fb43-11e8-91e6-9ea1823b3ce3.png)

**Comment by pavel-demin** [comment]
I'm afraid that I can't do anything about this problem.

Quisk implements the  [Hermes-Lite2 protocol](https://github.com/softerhardware/Hermes-Lite2/wiki/Protocol) that isn't exactly the same as the HPSDR/Metis protocol implemented in PowerSDR mRX PS and in my SDR applications. That's why the ALEX interface doesn't work with Quisk.

**Comment by satfan52** [comment]
To the attention of QUISK  users: The problem has been fixed in release 4.1.31 of QUISK.
