### ISSUE TITLE
SDR Transceiver for NFC-communication

### ISSUE THREAD

**Issue by pwigger** [pavel-demin/red-pitaya-notes#806]
Dear Pavel
We are students and currently working on our Bachelorthesis. Our goal is to use Redpitaya for NFC communication trying to maximize the distance of the communication. We stumbled upon your sdr transceiver and are using it for our project. We use GNU radio to handle the communication and implemented the start of the communication protocol.

Everything works and by now we are able to activate a card on roughly 50cm. (With a 20-Watt amplifier attached to the RP)
Now we try to optimize the receiving part for maximising the reply distance. Since the activation antenna creates a lot of noise we evaluate the idea of diversity reception. We would like to have a directional and a omnidirectional antenna for capturing the noise in order to be able to improve the signal from the directional antnna.

We have several questions concerning this. I read that with GNU Radio we should be able to recive with a bandwidth of 2.5mhz. Is there a way of adjusting this value and eg narrow the bandwidth? We couldnt figure out how to do this.
For diversity reception it would be great to have the signal at 14.4075 mhz as accurate ad possible in order to filter the noise out. The best thing to do would probably be to implement a diversitiy reception in FPGA. Unfortunately we are not capable to dive into FPGA programming within this project. So is there a way of manipulating the existing FIR filter without writing the FPGA code from scratch? In general: Is there a way of optimizing the sdr transceiver for 13.56/14.4075 mhz? 

Thanks for the great work. Any help would be highly appreciated.

All the best
Patrick and Roland

**Comment by pavel-demin** [comment]
You have a very interesting project.

What are the parameters (data rate, oversampling factor, coding method, etc) of your protocol and decoding algorithm?

Last time I looked at 14443A, I obtained the following numbers:
- two receivers are probably required to tune one to the carrier frequency (13.56 MHz) and other to one of the sub-carrier frequencies (12.71 or 14.41 MHz).
- with 1250 kSPS sampling rate, all the frequencies higher than ~600 kHz could be filtered out and the oversampling factor would be slightly less than 12 (for the 106 kBd data rate).
- transmitter should probably work at 2500 kSPS sampling rate to be able to transmit at both sub-carrier frequencies at the same time.

I'm not sure if these numbers are correct. They probably could be optimized. Do you have more or less similar numbers?

> I read that with GNU Radio we should be able to recive with a bandwidth of 2.5mhz. Is there a way of adjusting this value and eg narrow the bandwidth? We couldnt figure out how to do this.

It's possible to adjust the bandwidth by changing the sample rate. If you're using the GNU Radio blocks from the [projects/sdr_transceiver/gnuradio](https://github.com/pavel-demin/red-pitaya-notes/tree/master/projects/sdr_transceiver/gnuradio) directory, then these blocks have a parameter called "Sample Rate". The supported values are 20, 50, 100, 250, 500 and 1250 kSPS.

I think that it should be possible to implement the diversity reception in software. However, my SDR transceiver application for Red Pitaya can't be used for the diversity reception because the two receivers in this application aren't synchronized.

If you could make a list of your requirements (number of receivers, number of transmitters, sample rates, etc) , then I could try to check which of my projects could be adapted to these requirements.
