### ISSUE TITLE
Impossible to regenerate dac_player vivado project

### ISSUE THREAD

**Issue by jmonfer** [pavel-demin/red-pitaya-notes#816]
Hi Pavel,
I’m interested in your redpitaya projects that involve the high speed dacs or adcs with dma access to ddr3.
For this reason, I’m trying to regenerate the vivado dac_player project but I can’t (make NAME=dac_player xpr). The tcl script doesn’t finish. It shows the following error:

‘ERROR: can’t connect concat_0/In1 and fifo_1/axis_data_count’

I’ve found a similar error in the laser_test project.

**Comment by pavel-demin** [comment]
Thanks for finding this problem.

In Vivado 2018.3, the default configuration of the data FIFO IP has changed and the count ports are disabled by default.

It's now fixed with the following commits:

https://github.com/pavel-demin/red-pitaya-notes/commit/4e5e018c6596ac11907c2313d0f46d73d9d37f1c
https://github.com/pavel-demin/red-pitaya-notes/commit/6caacc83ea76c9c57fe4f531413d93b30c436b6d
