### ISSUE TITLE
Using both DAC for producing two different signals.

### ISSUE THREAD

**Issue by motagiyash** [pavel-demin/red-pitaya-notes#872]
Hi Pavel,
Hope your having a great day.
 I was trying to impliment sine and cosine both signals on two different dacs.
for ex: from dds (29:16 sin to dac 1 so out1 and 13:0 cosine to dac 2)
 so output on both outputs.

how should i go ahed with this issue. Should i modify dac Ip.

**Comment by pavel-demin** [comment]
In case of DDS, just connect it directly to the DAC module.

Otherwise, it's possible to use AXI4-Stream Combiner to combine signals from different sources into one stream. Here is how it's done in the SDR transceiver project:

https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver/block_design.tcl#L66-L86
