### ISSUE TITLE
Alpine Linux WSPR - some spots not uploading 

### ISSUE THREAD

**Issue by vronp** [pavel-demin/red-pitaya-notes#882]
### Description of the setup:

 * Device:Red Pitaya
 * SD card image:Alpine Linux WSPR receiver
 * Application:
 * Other relevant information:

### Description of the problem:

Hi, I noticed a set of spots were not appearing on the wsprnet.org site.  The missing spots were in the very first group heard after turning the system on.  Here is the list.  The 3 spots with the 23:52 time stamp did not show up.  I will search for a log that perhaps contains information about the upload process.

Pavel, thank you for your work on this.  If you feel I should instead be posting these types of things to groups.io, please let me know.

190803 2352   2 -20  0.5  14.097109  VO1DZA GN37 37          0  2567    0
190803 2352   2 -24  0.3  14.097180  NU1T FN42 23           -1     8    0
190803 2352   2 -26  0.5  14.097189  DL5SFB JN48 37          0     6    0
rp-f04d6c:/dev/shm# cat wspr_spots.txt
190803 2356   1 -27  1.4  14.097026  VE3KAE FN25 20          0  3010    8
190803 2356   6  -4  0.3  14.097076  <...> FN42FK 40         0     1    0
190803 2356   4 -13  1.0  14.097154  N1AGV FN32 23           0     1    0
rp-f04d6c:/dev/shm# cat wspr_spots.txt
190803 2356   1 -27  1.4  14.097026  VE3KAE FN25 20          0  3010    8
190803 2356   6  -4  0.3  14.097076  <...> FN42FK 40         0     1    0
190803 2356   4 -13  1.0  14.097154  N1AGV FN32 23           0     1    0
rp-f04d6c:/dev/shm# cat wspr_spots.txt
190804 0000   2 -23  1.3  14.097154  AA1HF FN43 23           0     1    0
rp-f04d6c:/dev/shm# 

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment]
From the information that you provide, I don't see why you think that the problem is in my code.

I think that the spots are lost because of a network connection problem. I've just tried to connect to wsprnet.org but it refuses my connections with error 503. So, looks like the server is overloaded and some spots could be lost because the server doesn't accept them.

BTW. My script uploads the spots from ALL_WSPR.TXT and not from wspr_spots.txt.
