### ISSUE TITLE
No IQ transfer with PiHPSDR

### ISSUE THREAD

**Issue by mompelix** [pavel-demin/red-pitaya-notes#889]
Hello,
i am using Pihpsdr together with Pavel HPSDR-Simulation on RedPitaya for about 2 years with great fun. After the update to the latest version of PIHPSDR and the actual SW from Pavel, i am no more able to use my transciever. The Ethernet connection is established, but the reciever does not work, it seems like the system hangs. I think the transfer of IQ-data is not working. I already had this effect with the old combination but this could be mented by a restart.
Does anyone have a solution??
Regards
Herko, DK3HU
@mompelix

**Comment by dl1ycf** [comment]
Hi,
I am actively involved in the development of piHPSDR and for me it works. Since I have a HAMlab (STEMlab), I have burnt an "Alpine linux" system on a SD card and it still works. I have even
now included code to automatically start the SDR app on the RedPitaya for the "Alpine Linux" RedPitayas, in addition to the STEMlab code already there.

If you dare building piHPSDR from the code obtain a copy from my github account
github.com/dl1ycf/pihpsdr, in the directory release/documentation you will find a PDF with a step-by-step instruction how to compile it from the sources.

Yours,

Christoph DL1YCF.
