### ISSUE TITLE
Red Pitaya has 4 ports. How to specify the "Red Pitaya sink" and "Red Pitaya source" to specific port.

### ISSUE THREAD

**Issue by friedrich1993322** [pavel-demin/red-pitaya-notes#966]
![Figure1](https://user-images.githubusercontent.com/29260105/85066960-2ddc6380-b1b0-11ea-8fab-e2dea13b59fe.jpg)
![Figure2](https://user-images.githubusercontent.com/29260105/85067016-49476e80-b1b0-11ea-8d0a-bbc51ebea823.png)
![Figure3](https://user-images.githubusercontent.com/29260105/85067030-4cdaf580-b1b0-11ea-9cbb-f2e683fda876.png)

### Description of the setup:

 * Device:Red Pitaya 125-14
 * SD card image:
 * Application:SDR transceiver
 * Other relevant information:

### Description of the problem:
I connected the "In1" and "Output1" of the Red Pitaya. (Shown in Figure1). But It seems that I can't receive the signal correctly. My program is shown in Figure 2 and the result is shown in Figure 3

Could you tell me, where is wrong?

### Steps to reproduce the problem:

 1.connect the "In1" and "Output1" of the Red Pitaya
 2.run a communication system
 3. observe the result. In my case, "after resample" is the output signal and "receiver" is the input signal. I can't receive the correct signal.

**Comment by pavel-demin** [comment]
To answer the question in the title of this issue (How to specify the "Red Pitaya sink" and "Red Pitaya source" to specific port?). For IN1 and OUT1, use port 1001 in the source and receiver blocks. For IN2 and OUT2, use port 1002 in the source and receiver blocks. An example flow graph can be found in [trx_dual_template.grc](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver/gnuradio/trx_dual_template.grc).

In the flow graph shown in Figure 2, the sample rates for most blocks are set to the wrong values. If the sample rates of the source and receiver blocks are set to 1.25 MSPS, then the sample rates of the other blocks directly connected to the source and receiver blocks must be set to the same value.

For a very basic test of the inputs and outputs, I'd suggest starting with something simpler than the flow graph shown in Figure 2. I'd start with just four blocks:
 - Sine Signal Source connected to Red Pitaya Sink
 - Red Pitaya Source connected to QT GUI Frequency Sink

Since all these blocks are already present in [trx_dual_template.grc](https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver/gnuradio/trx_dual_template.grc), this very basic test can be started with the following commands:
```
git clone https://github.com/pavel-demin/red-pitaya-notes
cd red-pitaya-notes/projects/sdr_transceiver/gnuradio
export GRC_BLOCKS_PATH=.
gnuradio-companion trx_dual_template.grc
```
